In [1]:
import os
import pandas as pd

In [5]:
datasets = {}
for file in os.listdir('.'):
    if file.endswith('.log'):
        datasets[file.split('.')[0]] = pd.read_json(file, lines=True)

In [8]:
conn = datasets['conn']
conn

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,ip_proto
0,1.600466e+09,CEy5B522tLndmtaNnb,fe80::2dcf:e660:be73:d220,54064,ff02::1:3,5355,udp,dns,0.417919,60.0,...,S0,True,False,0,D,2,156,0,0,17
1,1.600466e+09,CG3Ybb1adA9cgmqTL5,fe80::2dcf:e660:be73:d220,64915,ff02::1:3,5355,udp,dns,0.418672,60.0,...,S0,True,False,0,D,2,156,0,0,17
2,1.600466e+09,C0LzFo2osBR8Y21kG1,10.42.85.10,64915,224.0.0.252,5355,udp,dns,0.418670,60.0,...,S0,True,True,0,D,2,116,0,0,17
3,1.600466e+09,CQSXg61Ik7W64C7gZ2,10.42.85.10,137,10.42.85.255,137,udp,dns,13.992419,1360.0,...,S0,True,True,0,D,20,1920,0,0,17
4,1.600466e+09,CT8bQf3xWBdmvFc5G3,10.42.85.10,137,10.42.85.255,137,udp,dns,1.559274,600.0,...,S0,True,True,0,D,12,936,0,0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32721,1.600494e+09,CsnF201Mb2asuM8a42,10.42.85.115,123,10.42.85.10,123,udp,NaN,0.000935,120.0,...,SF,True,True,0,Dd,1,148,1,148,17
32722,1.600489e+09,C0tcOm2W75NKsOUrv8,10.42.85.115,50972,203.78.103.109,443,tcp,NaN,5396.529843,21655.0,...,S1,True,False,0,ShAdDa,306,33907,503,481510,6
32723,1.600488e+09,CWAd4wa94vgDiOKth,10.42.85.115,50957,10.42.85.10,445,tcp,"gssapi,smb,krb",5441.245037,8396.0,...,S1,True,True,0,ShADdaTtTt,120,13706,100,11156,6
32724,1.600484e+09,Cr2IBINSRToz45rEk,10.42.85.10,62613,203.78.103.109,443,tcp,NaN,9733.238141,54286.0,...,S1,True,False,0,ShAdDa,604,78458,977,947233,6
32725,1.600483e+09,CLhVdYXKfeC8wXOQj,10.42.85.115,50875,203.78.103.109,443,tcp,NaN,10674.445423,228414.0,...,S1,True,False,0,ShAdDa,904,264586,1652,1741081,6

In [15]:
conn["id.orig_h"].value_counts().head(100)

id.orig_h
194.61.24.102                29313
10.42.85.115                  2539
10.42.85.10                    737
fe80::2dcf:e660:be73:d220      116
fe80::a926:8915:319b:2238       18
::                               3
Name: count, dtype: int64

In [10]:
conn["id.resp_h"].value_counts().head(20)

id.resp_h
10.42.85.10       30259
192.168.45.1        584
10.90.90.90         355
ff02::1:3            75
224.0.0.252          73
208.80.153.240       72
10.42.85.255         63
72.21.91.29          49
ff02::1:2            47
204.79.197.203       47
208.80.153.224       45
204.79.197.200       43
40.91.125.0          40
70.37.74.6           38
13.107.21.200        30
74.120.184.194       28
52.242.211.89        22
151.101.1.140        20
151.139.128.14       19
74.120.184.204       16
Name: count, dtype: int64

In [14]:
conn["total_bytes"] = conn.get("orig_bytes", 0) + conn.get("resp_bytes", 0)
top_flows_bytes = (
    conn[["id.orig_h", "id.resp_h", "id.resp_p", "proto", "service", "total_bytes", "orig_bytes", "resp_bytes", "duration"]]
    .sort_values("total_bytes", ascending=False)
    .head(20)
)
top_flows_bytes

,id.orig_h,id.resp_h,id.resp_p,proto,service,total_bytes,orig_bytes,resp_bytes,duration
31709,10.42.85.115,104.119.185.124,443,tcp,ssl,37991129.0,1858.0,37989271.0,109.659907
32078,194.61.24.102,10.42.85.10,3389,tcp,ssl,12853439.0,2366216.0,10487223.0,1810.715048
32089,10.42.85.10,10.42.85.115,3389,udp,rdpeudp,6448171.0,73592.0,6374579.0,950.971623
1698,10.42.85.115,104.18.12.165,443,tcp,ssl,4664235.0,2328.0,4661907.0,126.184417
1340,10.42.85.115,23.47.193.50,443,tcp,ssl,4596703.0,4575.0,4592128.0,33.567848
1333,10.42.85.115,143.204.131.79,443,tcp,ssl,4289666.0,993.0,4288673.0,29.046927
1250,10.42.85.115,151.101.1.67,443,tcp,ssl,4101555.0,10810.0,4090745.0,54.299074
31935,10.42.85.115,23.47.52.14,443,tcp,ssl,3130065.0,2387.0,3127678.0,41.379130
155,10.42.85.115,23.47.48.60,443,tcp,ssl,3050041.0,2387.0,3047654.0,2.925606
32335,10.42.85.115,23.47.52.90,443,tcp,ssl,2645142.0,1030.0,2644112.0,1.100630
662,10.42.85.115,13.107.21.200,443,tcp,ssl,1956916.0,133182.0,1823734.0,189.266337
32725,10.42.85.115,203.78.103.109,443,tcp,NaN,1903403.0,228414.0,1674989.0,10674.445423
681,10.42.85.115,34.96.91.138,443,tcp,ssl,1834564.0,2504.0,1832060.0,160.629322
1337,10.42.85.115,23.47.193.50,443,tcp,ssl,1653448.0,6384.0,1647064.0,33.567886
671,10.42.85.115,74.120.184.204,443,tcp,ssl,1300602.0,840.0,1299762.0,160.775039
1675,10.42.85.115,74.120.184.194,443,tcp,ssl,1225481.0,6202.0,1219279.0,68.908586
31777,10.42.85.115,204.79.197.200,443,tcp,ssl,1210662.0,16866.0,1193796.0,153.286589
294,10.42.85.115,172.232.42.32,443,tcp,ssl,1136263.0,11886.0,1124377.0,47.022114
1231,10.42.85.115,204.79.197.200,443,tcp,ssl,1132849.0,36546.0,1096303.0,100.512819
421,10.42.85.115,23.32.45.41,443,tcp,ssl,1071700.0,22918.0,1048782.0,58.781565